// Job item states
// JOB status flow: PENDING_SRU_HARVESTER -> PROCESSING_RECORDS -> IN_QUEUE -> IN_PROCESS -> DONE
export const JOB_STATES_SRU = {
  DONE: 'DONE',
  IN_PROCESS: 'IN_PROCESS',
  PENDING_SRU_HARVESTER: 'PENDING_SRU_HARVESTER',
  PENDING_RECORDS: 'PENDING_RECORDS',
  PROCESSING_RECORDS: 'PROCESSING_RECORDS'
};
